LANDING_PAGE_ICON_SIZE = 300
LANDING_PAGE_FONT_SIZE = 40

HEADING_LABEL_X = 0.5
HEADING_LABEL_Y = 0.09

FONT = 'Arial'
FONT_SIZE = 25
STYLE = 'bold'

CANVAS_HEIGHT = 1000
CANVAS_WIDTH = 1500

SIDE_IMAGE_HEIGHT = 500
SIDE_IMAGE_WIDTH = 500

SIDE_IMAGE_X = 0.25
SIDE_IMAGE_Y = 0.5

SIDE_TEXT_X = 0.25
SIDE_TEXT_Y = 0.675

BUTTON_X = 0.45

MENU_LABEL_X = 0.25

REPORT_ENTRY_BOX_X = 0.65
REPORT_ENTRY_BOX_HEIGHT = 100
REPORT_ENTRY_BOX_WIDTH = 700

BOOKS_SEARCH = ['Accession Number', 'Title', 'ISBN', 'Publisher', 'Year', 'Author']
BOOKS_ON_LOAN = ['Accession Number', 'Title', 'ISBN', 'Publisher', 'Year', 'Author']